# Generated by Django 3.2.7 on 2024-04-16 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vakilapp', '0002_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_schedule',
            name='user',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122, null=True)),
                ('Email', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vakilapp.appointment_schedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
