# Generated by Django 3.2.7 on 2024-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0003_auto_20240416_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_num', models.IntegerField()),
                ('Title', models.CharField(max_length=122, null=True)),
                ('writer_name', models.CharField(max_length=122, null=True)),
                ('date_blog', models.DateField()),
                ('para', models.TextField()),
            ],
        ),
    ]
