# Generated by Django 3.2.7 on 2024-04-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Date',
            field=models.DateField(default=None, null=True),
        ),
    ]
