# Generated by Django 3.2.7 on 2024-04-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0006_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
