# Generated by Django 3.2.7 on 2024-04-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0007_remove_appointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
