# Generated by Django 3.2.7 on 2024-04-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0008_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_num',
        ),
    ]
