# Generated by Django 3.2.7 on 2024-04-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0009_remove_blog_blog_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='writer_name',
            new_name='editor',
        ),
    ]
