# Generated by Django 3.2.7 on 2024-04-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0010_rename_writer_name_blog_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
