# Generated by Django 3.2.7 on 2024-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0011_auto_20240426_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Blog_Photo')),
                ('Title', models.CharField(max_length=122, null=True)),
                ('editor', models.CharField(max_length=122, null=True)),
                ('date_blog', models.DateField()),
                ('para', models.TextField()),
            ],
        ),
    ]
