# Generated by Django 3.2.7 on 2024-04-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('Blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vakilapp.blog')),
            ],
        ),
    ]
