# Generated by Django 3.2.7 on 2024-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0015_blog_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='Email',
            field=models.CharField(default=None, max_length=122),
        ),
    ]
