# Generated by Django 3.2.7 on 2024-04-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0016_auto_20240429_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Date',
            field=models.DateField(default=None, null=True),
        ),
    ]
