# Generated by Django 3.2.7 on 2024-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0018_blog_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122, null=True)),
                ('Email', models.CharField(default=None, max_length=122)),
                ('Date', models.DateField(default=None, null=True)),
            ],
        ),
    ]
