# Generated by Django 3.2.7 on 2024-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0019_blog_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_name', models.CharField(max_length=122, null=True)),
                ('noti_text', models.CharField(default=None, max_length=122)),
                ('noti_url', models.CharField(default=None, max_length=122)),
                ('Date', models.DateField(default=None, null=True)),
            ],
        ),
    ]
