# Generated by Django 3.2.7 on 2024-05-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakilapp', '0023_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
